### ISSUE TITLE
When can the code be available to the public?

### ISSUE THREAD

**Issue by Starboy-at-earth** [yuk6heo/GIS-RAmap#1]
Dear @yuk6heo, could you please tell me?

**Comment by yuk6heo** [comment]
The codes are currently being revised. I will try to upload it as quickly as possible.

**Comment by iegorval** [comment]
Dear @yuk6heo, could you please tell if the code will be available any time soon? I really liked your work, and I was following it for some time, and I would like to use it for creating the segmentation dataset for my thesis, but I am not sure anymore if the code will be released in the near future. Thank you for answer.

**Comment by yuk6heo** [comment]
It is now uploaded. I'm really sorry for uploading so late and I hope it will be helpful for your research.
